// lang-zh.ts

export const LANG_ZH_NAME = 'zh';

export const LANG_ZH_TRANS = {
    'zh':'中文',
    'en':'English',
    'language-preference':'语言偏好',
    'select-language':'请选择 您的语言偏好',
    'current-language':'您的语言偏好是 ',
    'reload-browser':'请刷新浏览器激活设置',
    'hello world': '你好，世界',
    'dashboard': '报表',
    'manage-device': '设备管理',
    'device-explorer': '所有设备',
    'device-registration': '设备注册',
    'device-batch-control': '批量操作',
    'asset':'资产管理',
    'asset-explorer':'所有资产',
    'asset-template':'资产模型',
    'manage-group':'分组管理',
    'manage-rule':'规则',
    'manage-alarm':'告警',
    'manage-diagnosis':'设备诊断',
    'manage-upgrade':'设备升级',
    'repository':'固件、软件仓库',
    'firmware-explorer':'固件',
    'software-explorer':'软件',
    'manage-user':'用户管理',
    'user-explorer':'所有用户',
    'role-management':'角色管理',
    'device-access-control':'权限管理',
    'request-access':'请求权限',
    'granting-access':'发放权限',
    'help':'帮助',
    'profile': '个人资料',
    'settings': '设置',
    'sign-out': '注销',
};