// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'zh':'中文',
    'en':'English',
    'language-preference':'Language Preference',
    'select-language':'Please Select Your Preference Language',
    'current-language':'Your Preference Language is ',
    'reload-browser':'Please reload your browser to active setting',
    'hello world': 'hello world',
    'dashboard': 'Dashboard',
    'manage-device': 'Device',
    'device-explorer': 'Explorer',
    'device-registration': 'Registration',
    'device-batch-control': 'Batch Control',
    'asset':'Asset',
    'asset-explorer':'Explorer',
    'asset-template':'Template',
    'manage-group':'Group',
    'manage-rule':'Rule',
    'manage-alarm':'Alarm',
    'manage-diagnosis':'Diagnosis',
    'manage-upgrade':'Upgrade',
    'repository':'Repository',
    'firmware-explorer':'Firmware',
    'software-explorer':'Software',
    'manage-user':'User',
    'user-explorer':'Explorer',
    'role-management':'Role',
    'device-access-control':'Device Access',
    'request-access':'Request Access',
    'granting-access':'Granting Access',
    'help':'Help',
    'profile': 'Profile',
    'settings': 'Settings',
    'sign-out': 'Sign Out',
};